name: pizza_repository
description: "The repository handles all pizza related operations."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # equatable: ^2.0.5
  # firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  # firebase_storage: ^12.3.5
  # rxdart: ^0.28.0
  # path: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:  
  uses-material-design: true
